from __future__ import annotations

from typing import Optional, Protocol


class PrefixCacheStorePort(Protocol):
    def lookup_prefix(self, content_hash: str) -> Optional[tuple[int, int]]: ...

    def record_prefix_hit(self, content_hash: str) -> None: ...

    def store_prefix(self, content_hash: str, token_count: int) -> None: ...

    def evict_old_prefixes(self, max_entries: int) -> None: ...

    def clear(self) -> None: ...
